### ISSUE TITLE
Problems pane always opening while extension is enabled

### ISSUE THREAD

**Issue by rodrigorodriguez** [abhinavk99/codewall#1]
Problems pane always opening while extension is enabled even when the file has no problems at all.

**Comment by abhinavk99** [comment]
I know how to fix that but I won't be able to work on it this weekend so I'll do it next week.

**Comment by kkredit** [comment]
Could you tie opening the problems pane to a setting in settings.json? Always opening the pane is too invasive. There are projects where I can't go through and resize all the lines to fit my rulers.

**Comment by abhinavk99** [comment]
Yeah sure, thanks for the idea.

**Comment by abhinavk99** [comment]
@kkredit It's done, update to version 1.1.0 and use `codewall.openProblemsPane` and set it to false. Alternatively, there's a checkbox that you can uncheck in the settings UI.
